In [1]:
import numpy as np
from hal import Hal_Matrix

In [2]:
data = np.array([[1.,2.],
                 [3.,4.],
                 [5.,6.],
                 [7.,8.]])
x = Hal_Matrix(n=2,d=2, data=data)

In [3]:
print(x.inverse())  

[[-0.875 -1.   ]
 [ 0.375  0.5  ]
 [ 0.625  0.75 ]
 [-0.125 -0.25 ]]


In [4]:
data = np.array([[1.,1.],
                 [1.,1.],
                 [1.,1.],
                 [1.,1.]])
y = Hal_Matrix(n=2,d=2, data=data)

In [5]:
print(x.dot(y))

[[ 4.  6.]
 [ 4.  6.]
 [12. 14.]
 [12. 14.]]


In [6]:
print(x)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [7]:
print(x + y)

[[2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [8]:
data = np.array([[1,2],
                 [3,4],
                 [5,6],
                 [7,8],
                 [9,10],
                 [11,12],
                 [13,14],
                 [15,16],
                 [17,18]])
x = Hal_Matrix(n=3,d=2, data=data)

In [9]:
print(x.inverse())  

NotInvertible: Matrix is not invertible